Chow NI tomography
ucgmsim/Velocity-Model pull request #34
Opened 2022-03-04 10:30 UTC by sungeunbae

Chow NI tomography (https://core.geo.vuw.ac.nz/d/feae69f61ea54f81bee1/ ) integrated

2022-03-06 22:41 UTC, jasonmotha commented
Github won't let me view the changes on this commit [c580cfa](https://github.com/ucgmsim/Velocity-Model/pull/34/commits/c580cfa408cf131a467f154c3f5f402ac12464bd) I believe it's more than just the files added. Can you add these files in as a separate PR and then the the code changes as a separate?

Regarding the actual VM domain merge code, I think it would be good to have it in this repo too. There are some python scripts in the Velocity Model folder in here.

2022-03-07 01:06 UTC, sungeunbae commented
> Github won't let me view the changes on this commit [c580cfa](https://github.com/ucgmsim/Velocity-Model/pull/34/commits/c580cfa408cf131a467f154c3f5f402ac12464bd) I believe it's more than just the files added. Can you add these files in as a separate PR and then the the code changes as a separate?
> 
> Regarding the actual VM domain merge code, I think it would be good to have it in this repo too. There are some python scripts in the Velocity Model folder/module in here.

Looks like github did some magic when it complained my PR was outdated.

2022-03-14 13:57 UTC, sungeunbae commented
Review this after merging https://github.com/ucgmsim/Velocity-Model/pull/39
<img width="828" alt="Screen Shot 2022-03-14 at 10 56 56 PM" src="https://user-images.githubusercontent.com/466989/158186982-8299733f-0dd8-449a-90bc-706312253215.png">

2022-03-16 21:25 UTC, sungeunbae commented
<img width="840" alt="Screen Shot 2022-03-17 at 6 23 56 AM" src="https://user-images.githubusercontent.com/466989/158693630-f02f017d-6f97-45c7-a860-ab7425db599f.png">


@jasonmotha @jpa198  This should be more reviewer friendly now.

2022-03-17 21:50 UTC, jasonmotha commented
It's much better now. Cheers.

Can we model the version numbers for 2.08 similarly to how Ethan upgraded the tomography for 2.05?

2.08 for the version (with all the 2.07 basins) sorry there's been a few more added since you started looking at this.
2.08_no_basins - for the version with no-basins

2022-03-18 00:57 UTC, sungeunbae commented on src/makefile.mac
> -CFLAGS = -std=c99 -g -Wall -O3 -fopenmp #-D_AIX
OK, to clarify, are you suggesting 2.08_no_basins (currently named 2.08_chow_ni) and 2.08 (currently named 2.09_chow_ni)? I am happy to change.

2022-03-18 01:01 UTC, sungeunbae commented on src/makefile.mac
> -CFLAGS = -std=c99 -g -Wall -O3 -fopenmp #-D_AIX
and for the makefile change, yeah..I admit it is irrelevant from this PR, but was needed to compile the code on my mac. Then, I wondered if it was worth a separate PR, and decided to let it go under your eyes..haha.

2022-03-18 01:05 UTC, jasonmotha commented on src/makefile.mac
> -CFLAGS = -std=c99 -g -Wall -O3 -fopenmp #-D_AIX
> OK, to clarify, are you suggesting 2.08_no_basins (currently named 2.08_chow_ni) and 2.08 (currently named 2.09_chow_ni)? I am happy to change.

Yep. That sounds right.

2022-03-18 01:11 UTC, sungeunbae commented on src/makefile.mac
> -CFLAGS = -std=c99 -g -Wall -O3 -fopenmp #-D_AIX
Cool. Just pushed the change. Will make a separate makefile.mac PR.

2022-03-18 01:12 UTC, jasonmotha approved these changes
Just had a look at the whole makefile situation. (it's a bit simpler that I remember).

You're probably the only person who'll use the make mac option going forward; so I don't think it's a big issue with your changes.

2022-03-18 01:13 UTC, jasonmotha requested changes
Oh, can you include the additional basins that have snuck into 2.07 ?

2022-03-18 06:50 UTC, sungeunbae commented
> Oh, can you include the additional basins that have snuck into 2.07 ?

Done

2022-03-18 07:09 UTC, jasonmotha approved these changes

2022-03-18 08:21 UTC, merged